describe("DREAM examples", function()
	it("loads the examples placeholder module", function()
		local mod = require("dream_examples")
		assert.is_table(mod)
		assert.equals("DREAM examples placeholder", mod.name)
	end)
end)
